name: Create Github Release

on:
  create:
    tags:
      - v*

jobs:

  build-arm6:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build backend plugin
        run: make build-backend-cross-linux-arm6
      - name: Upload dist folder
        uses: actions/upload-artifact@v2
        with:
          name: plugin-arm6
          path: ./dist/
      - name: package-and-zip-arm6
        run: make package-and-zip-arm6
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}


  create-release:
    runs-on: ubuntu-latest
    needs:
      - build-arm6

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.18.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.18.x
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-modules-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build frontend
        run: make build-frontend
      - name: Download linux binary
        uses: actions/download-artifact@v2
        with:
          name: plugin-arm6
          path: ./dist/
      - name: package-and-zip-arm6
        run: make package-and-zip-arm6
        env:
          GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
